// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.6
// source: protos/ping.proto

package demo

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Req struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *Req) Reset() {
	*x = Req{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_ping_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Req) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Req) ProtoMessage() {}

func (x *Req) ProtoReflect() protoreflect.Message {
	mi := &file_protos_ping_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Req.ProtoReflect.Descriptor instead.
func (*Req) Descriptor() ([]byte, []int) {
	return file_protos_ping_proto_rawDescGZIP(), []int{0}
}

func (x *Req) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Req) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type TodoAdd struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *TodoAdd) Reset() {
	*x = TodoAdd{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_ping_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TodoAdd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TodoAdd) ProtoMessage() {}

func (x *TodoAdd) ProtoReflect() protoreflect.Message {
	mi := &file_protos_ping_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TodoAdd.ProtoReflect.Descriptor instead.
func (*TodoAdd) Descriptor() ([]byte, []int) {
	return file_protos_ping_proto_rawDescGZIP(), []int{1}
}

func (x *TodoAdd) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TodoAdd) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type TodoDelete struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *TodoDelete) Reset() {
	*x = TodoDelete{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_ping_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TodoDelete) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TodoDelete) ProtoMessage() {}

func (x *TodoDelete) ProtoReflect() protoreflect.Message {
	mi := &file_protos_ping_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TodoDelete.ProtoReflect.Descriptor instead.
func (*TodoDelete) Descriptor() ([]byte, []int) {
	return file_protos_ping_proto_rawDescGZIP(), []int{2}
}

func (x *TodoDelete) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TodoDelete) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Res struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *Res) Reset() {
	*x = Res{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_ping_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Res) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Res) ProtoMessage() {}

func (x *Res) ProtoReflect() protoreflect.Message {
	mi := &file_protos_ping_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Res.ProtoReflect.Descriptor instead.
func (*Res) Descriptor() ([]byte, []int) {
	return file_protos_ping_proto_rawDescGZIP(), []int{3}
}

func (x *Res) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Res) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_protos_ping_proto protoreflect.FileDescriptor

var file_protos_ping_proto_rawDesc = []byte{
	0x0a, 0x11, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x70, 0x69, 0x6e, 0x67, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x04, 0x70, 0x69, 0x6e, 0x67, 0x22, 0x29, 0x0a, 0x03, 0x52, 0x65, 0x71,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x22, 0x2d, 0x0a, 0x07, 0x54, 0x6f, 0x64, 0x6f, 0x41, 0x64, 0x64, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x22, 0x30, 0x0a, 0x0a, 0x54, 0x6f, 0x64, 0x6f, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x29, 0x0a, 0x03, 0x52, 0x65, 0x73, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x32, 0x72, 0x0a, 0x04, 0x50, 0x69, 0x6e, 0x67, 0x12, 0x1e, 0x0a, 0x04, 0x45, 0x63, 0x68, 0x6f,
	0x12, 0x09, 0x2e, 0x70, 0x69, 0x6e, 0x67, 0x2e, 0x52, 0x65, 0x71, 0x1a, 0x09, 0x2e, 0x70, 0x69,
	0x6e, 0x67, 0x2e, 0x52, 0x65, 0x73, 0x22, 0x00, 0x12, 0x21, 0x0a, 0x03, 0x41, 0x64, 0x64, 0x12,
	0x0d, 0x2e, 0x70, 0x69, 0x6e, 0x67, 0x2e, 0x54, 0x6f, 0x64, 0x6f, 0x41, 0x64, 0x64, 0x1a, 0x09,
	0x2e, 0x70, 0x69, 0x6e, 0x67, 0x2e, 0x52, 0x65, 0x73, 0x22, 0x00, 0x12, 0x27, 0x0a, 0x06, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x12, 0x10, 0x2e, 0x70, 0x69, 0x6e, 0x67, 0x2e, 0x54, 0x6f, 0x64,
	0x6f, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x1a, 0x09, 0x2e, 0x70, 0x69, 0x6e, 0x67, 0x2e, 0x52,
	0x65, 0x73, 0x22, 0x00, 0x42, 0x19, 0x5a, 0x17, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x69, 0x61, 0x6d, 0x45, 0x7a, 0x61, 0x7a, 0x2f, 0x64, 0x65, 0x6d, 0x6f, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protos_ping_proto_rawDescOnce sync.Once
	file_protos_ping_proto_rawDescData = file_protos_ping_proto_rawDesc
)

func file_protos_ping_proto_rawDescGZIP() []byte {
	file_protos_ping_proto_rawDescOnce.Do(func() {
		file_protos_ping_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_ping_proto_rawDescData)
	})
	return file_protos_ping_proto_rawDescData
}

var file_protos_ping_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_protos_ping_proto_goTypes = []interface{}{
	(*Req)(nil),        // 0: ping.Req
	(*TodoAdd)(nil),    // 1: ping.TodoAdd
	(*TodoDelete)(nil), // 2: ping.TodoDelete
	(*Res)(nil),        // 3: ping.Res
}
var file_protos_ping_proto_depIdxs = []int32{
	0, // 0: ping.Ping.Echo:input_type -> ping.Req
	1, // 1: ping.Ping.Add:input_type -> ping.TodoAdd
	2, // 2: ping.Ping.Delete:input_type -> ping.TodoDelete
	3, // 3: ping.Ping.Echo:output_type -> ping.Res
	3, // 4: ping.Ping.Add:output_type -> ping.Res
	3, // 5: ping.Ping.Delete:output_type -> ping.Res
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protos_ping_proto_init() }
func file_protos_ping_proto_init() {
	if File_protos_ping_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protos_ping_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Req); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_ping_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TodoAdd); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_ping_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TodoDelete); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_ping_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Res); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_ping_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_ping_proto_goTypes,
		DependencyIndexes: file_protos_ping_proto_depIdxs,
		MessageInfos:      file_protos_ping_proto_msgTypes,
	}.Build()
	File_protos_ping_proto = out.File
	file_protos_ping_proto_rawDesc = nil
	file_protos_ping_proto_goTypes = nil
	file_protos_ping_proto_depIdxs = nil
}
